(function(){
  const params = new URLSearchParams(location.search);
  const gamePath = params.get("game") || "/examples/hello-game/index.html";
  const frame = document.getElementById("game"), device=document.getElementById("device"), sizeEl=document.getElementById("size"), logEl=document.getElementById("log"), configEl=document.getElementById("configuration");
  const hostOrigin = location.origin; let helloSeen=false, preset="desktop", orientation="landscape", manifest=null;
  const presets={desktop:[1280,720],tablet:[1024,768],mobile:[390,844]};
  function log(label,obj){const line=`[${new Date().toLocaleTimeString()}] ${label}\n${obj?JSON.stringify(obj,null,2):""}\n\n`;logEl.textContent+=line;logEl.scrollTop=logEl.scrollHeight}
  function applyViewport(){let [w,h]=presets[preset]; const nativePortrait=h>=w; if((orientation==='portrait')!==nativePortrait)[w,h]=[h,w]; const stage=document.querySelector('.stage'); const maxW=Math.max(260,stage.clientWidth-32), maxH=Math.max(320,window.innerHeight*.68); const scale=Math.min(1,maxW/w,maxH/h); device.style.width=(w*scale)+'px';device.style.height=(h*scale)+'px';sizeEl.textContent=`${w} × ${h} (escala ${Math.round(scale*100)}%)`; document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===preset)); document.getElementById('portrait').classList.toggle('active',orientation==='portrait');document.getElementById('landscape').classList.toggle('active',orientation==='landscape');}
  function optionValue(opt){return opt&&typeof opt==='object'?opt.value:opt} function optionLabel(opt){return opt&&typeof opt==='object'?opt.label:String(opt)}
  function renderConfiguration(){configEl.innerHTML=''; const conf=(manifest&&manifest.configuration)||{}; if(!Object.keys(conf).length){configEl.textContent='Este jogo não declara configurações.';return} Object.entries(conf).forEach(([key,field])=>{const row=document.createElement('label');row.className='config-row';const title=document.createElement('span');title.textContent=field.label||key;row.appendChild(title);let input;if(field.type==='select'){input=document.createElement('select');(field.options||[]).forEach(opt=>{const o=document.createElement('option');o.value=String(optionValue(opt));o.textContent=optionLabel(opt);if(optionValue(opt)===field.default)o.selected=true;input.appendChild(o)})}else if(field.type==='boolean'){input=document.createElement('input');input.type='checkbox';input.checked=field.default===true}else{input=document.createElement('input');input.type=field.type==='number'?'number':'text';if(field.default!==undefined)input.value=field.default;if(field.min!==undefined)input.min=field.min;if(field.max!==undefined)input.max=field.max;if(field.step!==undefined)input.step=field.step}input.dataset.configKey=key;input.dataset.configType=field.type;row.appendChild(input);if(field.help){const help=document.createElement('small');help.textContent=field.help;row.appendChild(help)}configEl.appendChild(row)})}
  function currentConfiguration(){const out={}; configEl.querySelectorAll('[data-config-key]').forEach(input=>{let v;if(input.dataset.configType==='boolean')v=input.checked;else if(input.dataset.configType==='number')v=Number(input.value);else v=input.value;out[input.dataset.configKey]=v});return out}
  async function loadManifest(){try{const u=new URL('manifest.json',gameUrl);const r=await fetch(u);if(!r.ok)throw new Error(`HTTP ${r.status}`);manifest=await r.json();renderConfiguration();log('HOST: MANIFEST',{gameId:manifest.id,configuration:manifest.configuration||{}})}catch(e){configEl.textContent='Não foi possível carregar manifest.json automaticamente.';log('HOST: MANIFEST ERROR',{message:e.message})}}
  document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{preset=b.dataset.preset; orientation=preset==='mobile'?'portrait':'landscape';applyViewport()});
  document.getElementById('portrait').onclick=()=>{orientation='portrait';applyViewport()}; document.getElementById('landscape').onclick=()=>{orientation='landscape';applyViewport()}; window.addEventListener('resize',applyViewport); applyViewport();
  const gameUrl=new URL(gamePath,location.href); gameUrl.searchParams.set('fctool_origin',hostOrigin); loadManifest().then(()=>log('HOST',{ready:'configure os valores e inicie a sessão'}));
  document.getElementById('launch').onclick=()=>{helloSeen=false;frame.src='about:blank';setTimeout(()=>{frame.src=gameUrl.toString();log('HOST: NOVA SESSÃO',{loading:frame.src,configuration:currentConfiguration(),viewport:{preset,orientation}})},30)};
  window.addEventListener('message',function(event){if(event.source!==frame.contentWindow)return;if(event.origin!==gameUrl.origin){log('REJEITADO: origin',{origin:event.origin});return}const msg=event.data;if(!msg||msg.namespace!=='fctool.game'||msg.protocolVersion!=='1.0')return;log('GAME -> HOST: '+msg.type,msg);if(msg.type==='HELLO'){helloSeen=true;const response={namespace:'fctool.game',protocolVersion:'1.0',type:'INITIALIZE',messageId:'host_'+Date.now(),timestamp:new Date().toISOString(),payload:{sessionId:'mock-session-001',configuration:currentConfiguration(),mode:'mock',viewport:{preset,orientation}}};frame.contentWindow.postMessage(response,gameUrl.origin);log('HOST -> GAME: INITIALIZE',response)}if(msg.type==='READY'&&msg.payload&&msg.payload.appliedConfiguration)log('CONFIGURAÇÃO CONFIRMADA PELO JOGO',msg.payload.appliedConfiguration)});
  document.getElementById('clear').onclick=()=>{logEl.textContent='';if(helloSeen)log('HOST','log limpo; sessão continua')};
})();
